In [2]:
import torch
print(torch.__version__)


2.5.1+cu121


In [3]:
if torch.cuda.is_available():
  print('GPU is available')
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print('GPU is not available')

GPU is available
Using GPU: Tesla T4


# Creating a Tensor

In [4]:
# using empty
a = torch.empty(2,3)
print(a)

tensor([[-1.6003e-33,  3.3393e-41, -1.6007e-33],
        [ 3.3393e-41,  2.8026e-45,  0.0000e+00]])


In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.7123, 0.1324, 0.8664],
        [0.2864, 0.5954, 0.8048]])

In [9]:
# use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# other ways

# using arrange
print('Using arrange ->', torch.arange(0,10,2))

# using linspace
print('Using linspace ->',torch.linspace(0,10,10))

# using eye
print('Using eye ->', torch.eye(10))

# using full
print('Using full ->', torch.full((2,3), 5))

Using arrange -> tensor([0, 2, 4, 6, 8])
Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye -> tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])
Using full -> tensor([[5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[    135535851347344,     135535851347344,                   0],
        [                  0,                   0, 7310593858020254331]])

In [16]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

# Tensor Data Types

In [18]:
# find data type
x.dtype

torch.int64

In [19]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [20]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
# using to()
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

# Mathematical Operations

## 1. Scaler Operations

In [22]:
x = torch.rand(2,2)
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [23]:
# addition
x + 2

# substraction
x - 2

# multiplication
x * 3

# division
x / 3

# int division
(x * 100) // 3

# mod
((x * 100) // 3) % 2

# power
x**2

tensor([[0.0690, 0.0018],
        [0.0433, 0.0139]])

## 2. Element wise operation

In [24]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014]])
tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])


In [25]:
# additon
a + b

# substraction
a - b

# mulitply
a * b

# division
a / b

# power
a ** b

# mod
a % b

tensor([[0.1217, 0.7356, 0.0401],
        [0.1829, 0.0615, 0.0776]])

In [26]:
# abs
c = torch.tensor([-1.3,2.54,-3.2,4.92])
torch.abs(c)

tensor([1.3000, 2.5400, 3.2000, 4.9200])

In [27]:
# negative
torch.neg(c)

tensor([ 1.3000, -2.5400,  3.2000, -4.9200])

In [28]:
# round
torch.round(c)

tensor([-1.,  3., -3.,  5.])

In [29]:
# ceil
torch.ceil(c)

tensor([-1.,  3., -3.,  5.])

In [30]:
# floor
torch.floor(c)

tensor([-2.,  2., -4.,  4.])

In [31]:
# clamp
torch.clamp(c, min=-1, max=2)

tensor([-1.,  2., -1.,  2.])

## 3. Reduction Operation

In [32]:
d = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
d

tensor([[4., 6., 0.],
        [1., 9., 9.]])

In [33]:
# sum
torch.sum(d)

# sum along columns
torch.sum(d, dim=0)

# sum along rows
torch.sum(d, dim=1)

tensor([10., 19.])

In [34]:
# mean
torch.mean(d)

# mean along columns
torch.mean(d, dim=0)

# mean along rows
torch.mean(d, dim=1)

tensor([3.3333, 6.3333])

In [35]:
# median
torch.median(d)



tensor(4.)

In [36]:
# max and min
print(torch.max(d))
print(torch.min(d))

tensor(9.)
tensor(0.)


In [37]:
# product
torch.prod(d)



tensor(0.)

In [38]:
# standard deviaiton
torch.std(d)

tensor(3.8687)

In [39]:
# variance
torch.var(d)

tensor(14.9667)

In [40]:
# argmax
torch.argmax(d)

tensor(4)

In [41]:
# argmin
torch.argmin(d)

tensor(2)

## 4. Matrix Operations

In [42]:
e = torch.randint(size=(2,3), low=0, high=10)
f = torch.randint(size=(3,2), low=0, high=10)

print(e)
print(f)

tensor([[8, 0, 7],
        [0, 0, 9]])
tensor([[5, 7],
        [3, 9],
        [4, 0]])


In [43]:
# matrix mulitplication
torch.matmul(e,f)

tensor([[68, 56],
        [36,  0]])

In [44]:
# dot product
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

torch.dot(vector1, vector2)

tensor(11)

In [45]:
# transpose
torch.transpose(e, 0, 1)

tensor([[8, 0],
        [0, 0],
        [7, 9]])

In [46]:
# determinant
m = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
print(m)
torch.det(m)

tensor([[5., 7., 5.],
        [9., 9., 7.],
        [5., 9., 8.]])


tensor(-34.0000)

In [47]:
# inverse
torch.inverse(m)

tensor([[-0.2647,  0.3235, -0.1176],
        [ 1.0882, -0.4412, -0.2941],
        [-1.0588,  0.2941,  0.5294]])

## 5. Comparision Operations

In [48]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 7, 9],
        [2, 6, 7]])
tensor([[7, 8, 3],
        [6, 1, 5]])


In [49]:
# greater than
i > j

# less than
i < j

# equal to
i == j

# not equal to
i != j

# greater than or equal to
i >= j

# less than or equal to
i <= j

tensor([[False,  True, False],
        [ True, False, False]])

## 6. Special Functions

In [50]:
t = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
t

tensor([[5., 0., 4.],
        [3., 8., 8.]])

In [51]:
# log
torch.log(t)

tensor([[1.6094,   -inf, 1.3863],
        [1.0986, 2.0794, 2.0794]])

In [52]:
# exp
torch.exp(t)

tensor([[1.4841e+02, 1.0000e+00, 5.4598e+01],
        [2.0086e+01, 2.9810e+03, 2.9810e+03]])

In [53]:
# sqrt
torch.sqrt(t)

tensor([[2.2361, 0.0000, 2.0000],
        [1.7321, 2.8284, 2.8284]])

In [54]:
# sigmoid
torch.sigmoid(t)

tensor([[0.9933, 0.5000, 0.9820],
        [0.9526, 0.9997, 0.9997]])

In [55]:
# softmax
torch.softmax(t, dim=0)

tensor([[8.8080e-01, 3.3535e-04, 1.7986e-02],
        [1.1920e-01, 9.9966e-01, 9.8201e-01]])

In [56]:
# relu
torch.relu(t)

tensor([[5., 0., 4.],
        [3., 8., 8.]])

# Inplace Operations

In [57]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])
tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])


In [58]:
m.add_(n)

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [59]:
m

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [60]:
n

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

# Copying a Tensor

In [61]:
a = torch.rand(2,3)
a

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [62]:
b = a

In [63]:
b

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [64]:
a[0][0] = 0

In [65]:
a

tensor([[0.0000, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [66]:
b

tensor([[0.0000, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [67]:
id(a), id(b)

(135532220534432, 135532220534432)

In [68]:
b = a.clone()

In [69]:
a[0][0] = 2

In [70]:
a

tensor([[2.0000, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [71]:
b

tensor([[0.0000, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

# Tensor Operations on GPU

In [72]:
torch.cuda.is_available()

True

In [73]:
device = torch.device('cuda')

In [74]:
# create a tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [75]:
# moving existing tensor to GPU
a = torch.rand((2,3))
b = a.to(device)
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]], device='cuda:0')

In [76]:
b + 5

tensor([[5.2855, 5.2324, 5.9141],
        [5.7668, 5.1659, 5.4393]], device='cuda:0')

In [77]:
import time

# define the size of matrices
size = 10000

# create random matrices on CPU
matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

# measure the time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time
print(f"CPU time: {cpu_time} seconds")

# move matrices to GPU
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# measure the time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time
print(f"GPU time: {gpu_time} seconds")

# compare the results
print("\nSpeedup (CPU time / GPU time):", cpu_time/gpu_time)

CPU time: 25.39175534248352 seconds
GPU time: 0.7004787921905518 seconds

Speedup (CPU time / GPU time): 36.249142194695


# Reshaping Tensors

In [78]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [79]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [80]:
  # flatten
  a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
# permute
b = torch.rand(2,3,4)
b

tensor([[[0.3932, 0.7483, 0.7985, 0.4626],
         [0.9414, 0.5752, 0.8881, 0.7989],
         [0.9514, 0.0141, 0.8903, 0.1649]],

        [[0.3162, 0.1331, 0.6763, 0.4254],
         [0.2375, 0.5430, 0.1174, 0.6532],
         [0.5115, 0.3094, 0.7907, 0.7351]]])

In [82]:
b.permute(2,0,1)

tensor([[[0.3932, 0.9414, 0.9514],
         [0.3162, 0.2375, 0.5115]],

        [[0.7483, 0.5752, 0.0141],
         [0.1331, 0.5430, 0.3094]],

        [[0.7985, 0.8881, 0.8903],
         [0.6763, 0.1174, 0.7907]],

        [[0.4626, 0.7989, 0.1649],
         [0.4254, 0.6532, 0.7351]]])

In [88]:
# unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [90]:
# squeeze
d = torch.rand(1, 20)
d.squeeze(0).shape

torch.Size([20])

# NumPy & PyTorch

In [91]:
import numpy as np

In [92]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [93]:
b = a.numpy()
b

array([1, 2, 3])

In [94]:
type(b)

numpy.ndarray

In [95]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [96]:
torch.from_numpy(c)

tensor([1, 2, 3])